services:
  db:
    image: postgres:15
    container_name: user_tasks_db
    env_file:
      - ./shared_models/.env-non-dev
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgresdata: